default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>

development: &development
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  database: app_production
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>